services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/database.db
      - PORT=5000
      - PUBLIC_BASE_URL=https://demos.hipcall.com.tr/user-management-system
      - SCRIPT_NAME=/user-management-system
      - SECRET_KEY=${SECRET_KEY}
      - APP_USERNAME=${APP_USERNAME}
      - APP_PASSWORD_HASH=${APP_PASSWORD_HASH}
      - EXTENSION_SUCCESS=${EXTENSION_SUCCESS}
      - EXTENSION_FAIL=${EXTENSION_FAIL}
    restart: always
