version: '3.8'

services:
  insight-card:
    build: .
    ports:
      - "5009:5009"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=5009
      - SECRET_KEY=${SECRET_KEY}
      - APP_USERNAME=${APP_USERNAME}
      - APP_PASSWORD_HASH=${APP_PASSWORD_HASH}
      - APP_SCRIPT_NAME=${APP_SCRIPT_NAME}
      - HIPCALL_ACCOUNTS=${HIPCALL_ACCOUNTS}
    restart: always
