version: '3.8'

services:
  cdr-app:
    build: .
    ports:
      - "5007:5007"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=5007
      - APP_SCRIPT_NAME=${APP_SCRIPT_NAME}
      - HIPCALL_ACCOUNTS=${HIPCALL_ACCOUNTS}
      - SECRET_KEY=${SECRET_KEY}
      - APP_USERNAME=${APP_USERNAME}
      - APP_PASSWORD_HASH=${APP_PASSWORD_HASH}
    restart: always
